apiVersion: v1
kind: Pod
metadata:
  annotations:
  name: env
spec:
  containers:
  - image: embano1/env:1.0
    imagePullPolicy: Always
    name: env
    resources: {}
    resources:
      limits:
        # memory: "128Mi" # more precise
        memory: "128M"
        cpu: "500m"
    env:
      - name: HEAP
        valueFrom:
          resourceFieldRef:
          # update env with reference from limits
            resource: limits.memory
      - name: STACK
      # ordinary env setting
        value: "12m"
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
